sudo: required
services:
  - docker

before_install:
  - docker build -t predmaq/predmaq-test -f ./client/Dockerfile.dev ./client

script:
  - docker run predmaq/predmaq-test npm test -- --coverage

after_success:
  - docker build -t predmaq/multi-client ./client
  - docker build -t predmaq/multi-server ./server
  # Log docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Image push to docker hub
  - docker push predmaq/multi-client
  - docker push predmaq/multi-server
  