version: '3.9'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3008:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  tests:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    command: ["npm","run", "test"]
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    expose:
      - "5001"
    volumes:
      - /server/node_modules
      - ./server:/app
